- name: Delete DNS A Record
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    recordname: "{{ recordname }}"
    dns_server: "192.168.1.11"
    zone_name: "vmware.local"

  tasks:
    - name: Delete DNS A Record
      ansible.builtin.win_shell: |
        $dnsServer = '{{ dns_server }}'
        $zoneName = '{{ zone_name }}'
        $recordName = '{{ recordname }}'

        try {
          $record = Get-DnsServerResourceRecord `
            -ComputerName $dnsServer `
            -ZoneName $zoneName `
            -Name $recordName `
            -RRType "A" `
            -ErrorAction Stop

          if ($record) {
            foreach ($r in $record) {
              Remove-DnsServerResourceRecord `
                -ZoneName $zoneName `
                -RRType "A" `
                -Name $recordName `
                -RecordData $r.RecordData.IPv4Address.IPAddressToString `
                -ComputerName $dnsServer `
                -Force `
                -ErrorAction Stop
            }

            Write-Output "A record(s) deleted: $recordName.$zoneName"
          } else {
            Write-Output "No A record found for $recordName.$zoneName"
          }
        } catch {
          Write-Output "Failed to delete DNS A record: $($_.Exception.Message)"
        }
