---
- name: Get certificates expiring within 2 months from CA
  hosts: windows
  gather_facts: no
  tasks:
    - name: Run certutil to get expiring certificates in 2 months
      win_shell: |
        $today = Get-Date
        $twoMonthsLater = $today.AddMonths(2)
        $todayFormatted = $today.ToString("MM/dd/yyyy")
        $twoMonthsLaterFormatted = $twoMonthsLater.ToString("MM/dd/yyyy")

        $caConfig = "vmware.local\vmware-ADDNS-CA-1"
        $restrictFilter = "NotAfter>=$todayFormatted&NotAfter<=$twoMonthsLaterFormatted"

        $certutilCmd = "certutil -view -restrict `"$restrictFilter`" -out RequestID,CommonName,NotAfter -config `"$caConfig`""

        Write-Host "Running command:"
        Write-Host $certutilCmd
        Write-Host ""

        Invoke-Expression $certutilCmd
      register: certs_output

    - name: Show certificates expiring within 2 months
      debug:
        msg: "{{ certs_output.stdout_lines }}"
