- name: Query certificates expiring in X days from local CA
  hosts: 192.168.1.11
  gather_facts: no

  vars:
    ca_config: "vmware.local\\vmware-ADDNS-CA-1"
    days_until_expiry: "{{ days_until_expiry_input | int }}"

  tasks:
    - name: Query expiring certificates using certutil and filter in PowerShell
      win_shell: |
        $daysUntilExpiry = {{ days_until_expiry }}
        $expiryDate = (Get-Date).AddDays($daysUntilExpiry)

        $raw = certutil -view -out "RequestID,CommonName,NotAfter" -config "{{ ca_config }}"
        $lines = $raw | Where-Object { $_ -match '^\d+,' }

        $results = @()
        foreach ($line in $lines) {
            $parts = $line -split ","
            if ($parts.Length -ge 3) {
                $requestId = $parts[0].Trim()
                $commonName = $parts[1].Trim()
                $notAfterRaw = $parts[2].Trim()

                try {
                    $notAfter = Get-Date $notAfterRaw
                    if ($notAfter -lt $expiryDate) {
                        $results += "RequestID: $requestId`nCommonName: $commonName`nNotAfter: $notAfter`n---"
                    }
                } catch {}
            }
        }

        $results -join "`n"
      register: cert_output

    - name: Display filtered expiring certificates in clean format
      debug:
        msg: "{{ cert_output.stdout_lines }}"
