---
- name: Get certificates expiring within N months from CA
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    months_ahead: 2   # default value, can be overridden by survey

  tasks:
    - name: Run certutil to get expiring certificates in N months
      win_shell: |
        $today = Get-Date
        $monthsAhead = {{ months_ahead }}
        $twoMonthsLater = $today.AddMonths($monthsAhead)
        $todayFormatted = $today.ToString("MM/dd/yyyy")
        $twoMonthsLaterFormatted = $twoMonthsLater.ToString("MM/dd/yyyy")

        $caConfig = "vmware.local\vmware-ADDNS-CA-1"
        $restrictFilter = "NotAfter>=$todayFormatted&NotAfter<=$twoMonthsLaterFormatted"

        $certutilCmd = "certutil -view -restrict `"$restrictFilter`" -out RequestID,CommonName,NotAfter -config `"$caConfig`""

        Write-Host "Running command:"
        Write-Host $certutilCmd
        Write-Host ""

        Invoke-Expression $certutilCmd
      register: certs_output

    - name: Show certificates expiring within given months
      debug:
        msg: "{{ certs_output.stdout_lines }}"
