---
- name: Query certificates expiring in X days from local CA
  hosts: 192.168.1.11
  gather_facts: no

  vars:
    ca_config: "vmware.local\\vmware-ADDNS-CA-1"
    days_until_expiry: "{{ days_until_expiry_input | int }}"

  tasks:
    - name: Query expiring certificates using certutil
      win_shell: |
        $daysUntilExpiry = {{ days_until_expiry }}
        $currentDate = Get-Date
        $expiryDate = $currentDate.AddDays($daysUntilExpiry)
        $expiryString = $expiryDate.ToString("MM/dd/yyyy")

        $cmd = "certutil -view -restrict `"NotAfter<=$expiryString`" -out `"RequestID,CommonName,NotAfter`" -config `"{{
          ca_config }}`""
        Invoke-Expression $cmd
      register: cert_output

    - name: Display expiring certificates in job output
      debug:
        msg: "{{ cert_output.stdout_lines }}"
