- name: Query certificates expiring in X days from local CA
  hosts: 192.168.1.11
  gather_facts: no

  vars:
    ca_config: "vmware.local\\vmware-ADDNS-CA-1"
    days_until_expiry: "{{ days_until_expiry_input | int }}"

  tasks:
    - name: Query expiring certificates using certutil and filter in PowerShell
      win_shell: |
        $expiry = (Get-Date).AddDays({{ days_until_expiry }})
        $text = certutil -view -out "RequestID,CommonName,NotAfter" -config "{{ ca_config }}" -split "`n" -join "`n"
        $pattern = 'Row \d+:.*?Issued Request ID: (0x[0-9a-f]+).*?Issued Common Name: "?(.+?)"?\s+Certificate Expiration Date: (.+?)\r?$'
        ([regex]::Matches($text, $pattern, 'Singleline') | Where-Object {
          try { ([datetime]$_.Groups[3].Value) -lt $expiry } catch { $false }
        }).ForEach({
          "RequestID: $($_.Groups[1].Value)`nCommonName: $($_.Groups[2].Value)`nNotAfter: $($_.Groups[3].Value)`n---"
        }) -join "`n"
      register: cert_output

    - name: Display filtered expiring certificates in clean format
      debug:
        msg: "{{ cert_output.stdout_lines }}"
