- name: Query certificates expiring in X days from local CA
  hosts: 192.168.1.11
  gather_facts: no

  vars:
    ca_config: "vmware.local\\vmware-ADDNS-CA-1"
    days_until_expiry: "{{ days_until_expiry_input | int }}"

  tasks:
    - name: Query expiring certificates using certutil
      win_shell: |
        $daysUntilExpiry = {{ days_until_expiry }}
        $currentDate = Get-Date
        $expiryDate = $currentDate.AddDays($daysUntilExpiry)
        # Format expiryDate as yyyy/MM/dd
        $expiryString = $expiryDate.ToString("yyyy/MM/dd")

        # Construct certutil command with proper filters and fields
        $cmd = "certutil -view -restrict `"Request.NotAfter<=${expiryString}`" -out `"Request.RequestID,Request.CommonName,Request.NotAfter`" -config `"{{
          ca_config }}`""
        
        Write-Output "Running command: $cmd"
        Invoke-Expression $cmd
      register: cert_output

    - name: Display expiring certificates in job output
      debug:
        msg: "{{ cert_output.stdout_lines }}"
