- name: Create a VM from a template - deploy lab environment
  hosts: localhost
  gather_facts: true
  vars:
    datacenter_name: "dc1"
  tasks:
    - name: Clone the template test-AD-DNS
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: False
        name: test-AD-DNS
        template: test-AD-DNS
        datacenter: "{{ datacenter_name }}"
        folder: /dc1/vm
        state: poweredon
        cluster: cl1
        wait_for_ip_address: no
