- name: Create a VM from a template - deploy lab environment
  hosts: localhost
  gather_facts: true
  vars:
    datacenter_name: "dc1"
  tasks:
    - name: Clone the template test-AD-DNS
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: False
        name: test-AD-DNS
        template: test-AD-DNS
        datacenter: "{{ datacenter_name }}"
        folder: /dc1/vm
#        state: poweredon
        cluster: cl1
        wait_for_ip_address: no

    - name: Clone the template test-REDHATSVR
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: False
        name: test-REDHATSVR
        template: test-REDHATSVR
        datacenter: "{{ datacenter_name }}"
        folder: /dc1/vm
        state: poweredon
        cluster: cl1
        wait_for_ip_address: no
        
    - name: Clone the template test-SMTP 
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: False
        name: test-SMTP
        template: test-SMTP 
        datacenter: "{{ datacenter_name }}"
        folder: /dc1/vm
        state: poweredon
        cluster: cl1
        wait_for_ip_address: no
        
    - name: Clone the template test-VYOS 
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: False
        name: test-VYOS
        template: test-VYOS 
        datacenter: "{{ datacenter_name }}"
        folder: /dc1/vm
        state: poweredon
        cluster: cl1
        wait_for_ip_address: no
        
    - name: Clone the template test-W10WS
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: False
        name: test-W10WS
        template: test-W10WS
        datacenter: "{{ datacenter_name }}"
        folder: /dc1/vm
        state: poweredon
        cluster: cl1
        wait_for_ip_address: no
        
    - name: Clone the template test-WIN2019SVR
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: False
        name: test-WIN2019SVR
        template: test-WIN2019SVR
        datacenter: "{{ datacenter_name }}"
        folder: /dc1/vm
        state: poweredon
        cluster: cl1
        wait_for_ip_address: no

