---
- name: Power off virtual machine
  gather_facts: no
  hosts: localhost
  tasks:
    - name: poweroff "test-AD-DNS-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-AD-DNS-1"
        state: absent
        force: true
  
    - name: poweroff "test-REDHATSVR-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-REDHATSVR-1"
        state: absent
        force: true

    - name: poweroff "test-SMTP-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-SMTP-1"
        state: absent
        force: true

    - name: poweroff "test-VYOS-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-VYOS-1"
        state: absent
        force: true

    - name: poweroff "test-W10WS-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-W10WS-1"
        state: absent
        force: true

    - name: poweroff "test-WIN2019SVR-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-WIN2019SVR-1"
        state: absent
        force: true

    - name: Remove "test-AD-DNS-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-AD-DNS-1"
        state: absent

    - name: Remove "test-REDHATSVR-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-REDHATSVR-1"
        state: absent

    - name: Remove "test-SMTP-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-SMTP-1"
        state: absent

    - name: Remove "test-VYOS-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-VYOS-1"
        state: absent

    - name: Remove "test-W10WS-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-W10WS-1"
        state: absent

    - name: Remove "test-WIN2019SVR-1"
      vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "dc1"
        cluster: "cl1"
        name: "test-WIN2019SVR-1"
        state: absent


