- name: Deploy VM from template
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy Virtual Machine from template in content library with PowerON State
    community.vmware.vmware_content_deploy_template:
      hostname: "vc1.vmware.local"
      username: "{{ lookup('env', 'VMWARE_USER') }}"
      password: "{{ lookup('env', 'VMWARE_PASS') }}"
      template: test-AD-DNS
      folder: vm
      datacenter: dc1
      name: test-AD-DNS-1
      state: poweredon
     delegate_to: localhost
