- name: Deploy VM from template
  hosts: vc1.vmware.local
  gather_facts: false
  tasks:
    - name: Deploy VM from template
      community.vmware.vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: false
        datacenter: "dc1"
        folder: /dc1/vm
        template: "test-AD-DNS"
        name: "test-AD-DNS-1"
        state: poweredon
        cluster: cl1
        wait_for_ip_address: no
