- name: Deploy VM from template
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Deploy Virtual Machine from template in content library with PowerON State
    vmware_guest:
      hostname: "vc1.vmware.local"
      username: "{{ lookup('env', 'VMWARE_USER') }}"
      password: "{{ lookup('env', 'VMWARE_PASS') }}"
      validate_certs: False
      template: test-AD-DNS
      datacenter: dc1
      cluster: cl1
      datastore: ds1-2tb
      folder: /dc1/vm
      name: test-AD-DNS-1
      state: poweredon
