- name: Create AD User with Groups
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    username: "{{ username }}"  # This should be passed in via CLI or external input
    groups:
      - "Domain Users"
      - "Domain Admins"

  tasks:
    - name: Create AD user if not exists
      win_shell: |
        if (-not (Get-ADUser -Filter "SamAccountName -eq '{{ username }}'")) {
          $pass = ConvertTo-SecureString -AsPlainText "Welcome123!" -Force
          New-ADUser -Name "{{ username }}" `
                     -SamAccountName "{{ username }}" `
                     -AccountPassword $pass `
                     -Enabled $true `
                     -Path "CN=Users,DC=vmware,DC=local"
        }

    - name: Add user to groups only if groups exist
      win_shell: |
        $groups = @({% for group in groups %}"{{ group }}"{% if not loop.last %}, {% endif %}{% endfor %})
        $user = Get-ADUser -Identity "{{ username }}"
        if ($user) {
          foreach ($group in $groups) {
            try {
              $groupObj = Get-ADGroup -Identity "$group"
              if ($groupObj) {
                Add-ADGroupMember -Identity "$group" -Members $user
              }
            } catch {
              Write-Host "Unable to add '{{ username }}' to group '$group': $_"
            }
          }
        }
