- name: Create AD User with Groups
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    username: "kadworld"
    groups:
      - "all"
      - "ungrouped"
  tasks:
    - name: Create AD user
      win_shell: |
        if (-not (Get-ADUser -Identity "{{ username }}" -ErrorAction SilentlyContinue)) {
          $pass = ConvertTo-SecureString -AsPlainText "Welcome123!" -Force
          New-ADUser -Name "{{ username }}" `
                     -SamAccountName "{{ username }}" `
                     -AccountPassword $pass `
                     -Enabled $true `
                     -Path "OU=Users,DC=vmware,DC=local"
        }

    - name: Add user to groups
      win_shell: |
        $groups = @({% for group in groups %}"{{ group }}"{% if not loop.last %}, {% endif %}{% endfor %})
        foreach ($group in $groups) {
          Add-ADGroupMember -Identity $group -Members "{{ username }}"
        }
