- name: Create AD User with Groups
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    username: "kadworld"
    groups:
      - "Domain Users"
      - "IT Department"
  tasks:
    - name: Create AD user and add to groups
      win_shell: |
        $pass = ConvertTo-SecureString -AsPlainText "Welcome123!" -Force
        New-ADUser -Name "{{ username }}" `
                   -SamAccountName "{{ username }}" `
                   -AccountPassword $pass `
                   -Enabled $true `
                   -Path "CN=Users,DC=yourdomain,DC=local"
        
        $groups = @({% for group in groups %}"{{ group }}"{% if not loop.last %}, {% endif %}{% endfor %})
        foreach ($group in $groups) {
          Add-ADGroupMember -Identity $group -Members "{{ username }}"
        }
