- name: Create AD User and Add to Domain Users
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    username: "{{ username }}"
    password: "Welcome123!"

  tasks:
    - name: Create AD user if not exists
      win_shell: |
        $username = "{{ username }}"
        $user = Get-ADUser -Filter "SamAccountName -eq '$username'"
        if (-not $user) {
          $pass = ConvertTo-SecureString -AsPlainText "{{ password }}" -Force
          New-ADUser -Name $username `
                     -SamAccountName $username `
                     -AccountPassword $pass `
                     -Enabled $true `
                     -Path "CN=Users,DC=vmware,DC=local"
          Write-Host "✅ User '$username' created successfully."
        } else {
          Write-Host "ℹ️ User '$username' already exists. Skipping creation."
        }

    - name: Add user to Domain Users group
      win_shell: |
        $username = "{{ username }}"
        try {
          Add-ADGroupMember -Identity "Domain Users" -Members $username -ErrorAction Stop
          Write-Host "✅ Added '$username' to 'Domain Users'"
        } catch {
          Write-Host "❌ Error adding '$username' to 'Domain Users': $($_.Exception.Message)"
        }
