- name: Create a new user account
  hosts: 192.168.1.11
  gather_facts: no

  tasks:
    - name: Create user account via PowerShell
      win_shell: |
        $username = "{{ user }}"
        $password = "InitialPassword123!"

        try {
          Write-Output "🛠️ Creating user '$username'..."

          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
            Write-Output "⚠️ User '$username' already exists."
          } else {
            New-LocalUser -Name $username `
              -Password (ConvertTo-SecureString $password -AsPlainText -Force) `
              -FullName $username `
              -AccountNeverExpires:$true
            Add-LocalGroupMember -Group "Users" -Member $username
            Write-Output "✅ New account '$username' has been created."
          }

        } catch {
          Write-Output "❌ Failed to create account '$username': $($_.Exception.Message)"
        }
      register: result

    - name: Show result
      debug:
        var: result.stdout_lines
