- name: Disable AD User
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    username: "{{ username }}"
  tasks:
    - name: Disable account
      win_shell: |
        Disable-ADAccount -Identity {{ username }}
