- name: Disable AD User
  hosts: ad_server
  gather_facts: no
  vars:
    username: "{{ username }}"
  tasks:
    - name: Disable account
      win_shell: |
        Disable-ADAccount -Identity {{ username }}
