---
- name: Reset user password
  hosts: all
  gather_facts: no
  tasks:
    - name: Reset password via PowerShell
      win_shell: |
        $username = "{{ user }}"
        $newPassword = "{{ new_password }}"
        try {
          Set-LocalUser -Name $username -Password (ConvertTo-SecureString $newPassword -AsPlainText -Force)
          Write-Output "Password for $username has been reset."
        } catch {
          Write-Output "Failed to reset password for $username: $($_.Exception.Message)"
        }

