- name: Reset AD1 User Password
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    username: "{{ username }}"
  tasks:
    - name: Reset password using PowerShell
      win_shell: |
        $securePass = ConvertTo-SecureString -AsPlainText "TempPass123!" -Force
        Set-ADAccountPassword -Identity {{ username }} -Reset -NewPassword $securePass
        Enable-ADAccount -Identity {{ username }}
