- name: Reset AD2 User Password
  hosts: ad_server
  gather_facts: no
  vars:
    username: "{{ username }}"
  tasks:
    - name: Reset password using PowerShell
      win_shell: |
        $securePass = ConvertTo-SecureString -AsPlainText "TempPass456!" -Force
        Set-ADAccountPassword -Identity {{ username }} -Reset -NewPassword $securePass
        Enable-ADAccount -Identity {{ username }}
