---
- hosts: localhost
  gather_facts: false
  vars:
    vm_name: "test-dcdns"
    iso_path: "[esxi-nuc-02-ds] /ISO/1.en_windows_server_2019_vl_x64_12.2019.iso"
    datacenter: "dc1"
    cluster: "cl2"
    datastore: "esxi-nuc-02-ds"
    networks:
      - name: "allvlans4095"
        type: "static"
        ip: "172.16.30.10"
        netmask: "255.255.255.0"
        gateway: "172.16.30.254"
  tasks:
    - name: Create VM from ISO
      community.vmware.vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        name: "{{ vm_name }}"
        folder: "lab-deploy"
        guest_id: "windows2019srv_64Guest"
        hardware:
          memory_mb: 8192
          num_cpus: 4
          scsi: "paravirtual"
        networks: "{{ networks }}"
        datastore: "{{ datastore }}"
        customization_spec: "vmspecwin2019"
        cdrom:
          - controller_number: 0
            unit_number: 0
            controller_type: sata
            state: present
            type: iso
            iso_path: "{{ iso_path }}"
        disk:
          - size_mb: 100
            type: thin
            datastore: esxi-nuc-02-ds
            state: present
            scsi_controller: 1
            unit_number: 1
            scsi_type: 'paravirtual'
            disk_mode: 'persistent'
        state: poweredon
        wait_for_ip_address: true
