---
- hosts: localhost
  gather_facts: false
  vars:
    vm_name: "test-dcdns"
    iso_path: "[esxi-nuc-02-ds] /ISO/2019-1.iso"
    datacenter: "dc1"
    cluster: "cl2"
    datastore: "esxi-nuc-02-ds"
    networks:
      - name: "allvlans4095"
        type: "static"
        ip: "172.16.30.10"
        netmask: "255.255.255.0"
        gateway: "172.16.30.254"
  tasks:
    - name: deploy new vm
      community.vmware.vmware_guest:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        name: "{{ vm_name }}"
        folder: "lab-deploy"
        guest_id: "windows2019srv_64Guest"
        hardware:
          memory_mb: 8192
          num_cpus: 4
        networks: "{{ networks }}"
        datastore: "{{ datastore }}"
        cdrom:
          - controller_number: 0
            unit_number: 0
            controller_type: sata
            state: present
            type: iso
            iso_path: "{{ iso_path }}"
        disk:
          - size_gb: 100
            type: thin
            datastore: esxi-nuc-02-ds
            controller_number: 1
            unit_number: 1
            controller_type: 'lsilogicsas'
            disk_mode: 'persistent'
        state: poweredon
        wait_for_ip_address: true

    - name: Set boot firmware to EFI
      community.vmware.vmware_guest_boot_manager:
        hostname: "vc1.vmware.local"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASS') }}"
        validate_certs: no
        name: "{{ vm_name }}"
        boot_firmware: efi
        secure_boot_enabled: false
      delegate_to: localhost

