- name: Create new user and add to group
  hosts: 192.168.1.11
  gather_facts: false
  tasks:
    - name: Create new user
      ansible.windows.win_shell: |
        $SecurePass = ConvertTo-SecureString "Welcome12345!" -AsPlainText -Force
        New-ADUser -Name "{{ firstandlast }}" `
                   -SamAccountName "{{ username }}" `
                   -DisplayName "{{ firstandlastDisplayName }}" `
                   -GivenName "{{ givenname }}" `
                   -Surname "{{ surname }}" `
                   -AccountPassword $SecurePass `
                   -Enabled $true `
                   -Path "CN=Users,DC=vmware,DC=local" `
                   -CannotChangePassword $false `
                   -ChangePasswordAtLogon $true `
                   -PasswordNeverExpires $false `
                   -EmailAddress "{{ emailaddress }}" `
                   -EmployeeID "{{ employeeid }}" `
                   -Department "{{ department }}"
      register: user_creation_output

    - name: Add user to group
      ansible.windows.win_shell: |
        $groupDN = "CN={{ adgroup }},OU=Users,DC=vmware,DC=local"
        Add-ADGroupMember -Identity $groupDN -Members "{{ username }}"
      register: group_add_output

    - name: Print user creation output
      ansible.builtin.debug:
        var: user_creation_output.stdout_lines

    - name: Print group membership output
      ansible.builtin.debug:
        var: group_add_output.stdout_lines
