- name: create new user
  hosts: 192.168.1.11
  gather_facts: false
  tasks:
    - name: create new user
      ansible.windows.win_shell: |
        $SecurePass = ConvertTo-SecureString "Welcome12345!" -AsPlainText -Force
        New-ADUser -SamAccountName "kadsworld" `
                   -DisplayName "kadsworld" `
                   -GivenName "kads" `
                   -Surname "world" `
                   -AccountPassword $SecurePass `
                   -Enabled $true `
                   -Path "CN=Users,DC=vmware,DC=local" `
                   -CannotChangePassword $false `
                   -ChangePasswordAtLogon $true `
                   -PasswordNeverExpires $false `
                   -EmailAddress "kadsworld@vmware.local" `
                   -EmployeeID "1234567" `
                   -Department "IT"
      register: processes_output

    - name: Print the output
      debug:
        var: processes_output.stdout_lines
