- name: create new user and add to Administrators group
  hosts: 192.168.1.11
  gather_facts: false
  tasks:
    - name: create new user
      ansible.windows.win_shell: |
        $SecurePass = ConvertTo-SecureString "Welcome12345!" -AsPlainText -Force
        New-ADUser -Name "kadsworld" `
                   -SamAccountName "kadsworld" `
                   -DisplayName "kadsworld" `
                   -GivenName "kads" `
                   -Surname "world" `
                   -AccountPassword $SecurePass `
                   -Enabled $true `
                   -Path "CN=Users,DC=vmware,DC=local" `
                   -CannotChangePassword $false `
                   -ChangePasswordAtLogon $true `
                   -PasswordNeverExpires $false `
                   -EmailAddress "kadsworld@vmware.local" `
                   -EmployeeID "1234567" `
                   -Department "IT"
      register: user_creation_output

    - name: add user to Administrators group
      ansible.windows.win_shell: |
        Add-ADGroupMember -Identity "Administrators" -Members "kadsworld"
      register: group_add_output

    - name: Print user creation output
      debug:
        var: user_creation_output.stdout_lines

    - name: Print group membership output
      debug:
        var: group_add_output.stdout_lines
