---
- name: Run commands on Windows host
  hosts: 192.168.1.11
  gather_facts: false
  tasks:
    - name: Execute a command using win_command
      ansible.windows.win_command:
        cmd: "ipconfig /all"
      register: ipconfig_output

    - name: Print the output of ipconfig
      debug:
        var: ipconfig_output.stdout_lines

    - name: Execute a shell command using win_shell
      ansible.windows.win_shell:
        cmd: 'Stop-Service -Name "wuauserv" -Force'
      register: processes_output

    - name: Print the output of net stop
      debug:
        var: processes_output.stdout_lines
