---
- name: Generate CSR on Windows host using PowerShell
  hosts: 192.168.1.11
  gather_facts: no

  vars:
    country: "{{ country }}"
    state: "{{ state }}"
    city: "{{ city }}"
    organization: "{{ organization }}"
    unit: "{{ unit }}"
    common_name: "{{ common_name }}"
    san_dns:
      - "{{ san1 | default('') }}"
      - "{{ san2 | default('') }}"
    san_ips:
      - "{{ ip1 | default('') }}"
      - "{{ ip2 | default('') }}"
    inf_path: "C:\\temp\\csr_request.inf"
    csr_path: "C:\\temp\\csr_request.req"

  tasks:
    - name: Run PowerShell to generate CSR
      win_shell: |
        $Country = "{{ country }}"
        $State = "{{ state }}"
        $City = "{{ city }}"
        $Organization = "{{ organization }}"
        $Unit = "{{ unit }}"
        $CommonName = "{{ common_name }}"
        $SanDNS = @()
        $SanIPs = @()

        {% for dns in san_dns %}
        if ("{{ dns }}") { $SanDNS += "{{ dns }}" }
        {% endfor %}
        {% for ip in san_ips %}
        if ("{{ ip }}") { $SanIPs += "{{ ip }}" }
        {% endfor %}

        $InfPath = "{{ inf_path }}"
        $CsrPath = "{{ csr_path }}"

        if (-not (Test-Path "C:\\temp")) {
            New-Item -Path "C:\\temp" -ItemType Directory | Out-Null
        }

        $infContent = @"
        [Version]
        Signature=`"$Windows NT$`"

        [NewRequest]
        Subject = `"C=$Country, ST=$State, L=$City, O=$Organization, OU=$Unit, CN=$CommonName`"
        KeySpec = 1
        KeyLength = 2048
        Exportable = TRUE
        MachineKeySet = TRUE
        SMIME = FALSE
        PrivateKeyArchive = FALSE
        UserProtected = FALSE
        UseExistingKeySet = FALSE
        ProviderName = `"Microsoft RSA SChannel Cryptographic Provider`"
        ProviderType = 12
        RequestType = PKCS10
        KeyUsage = 0xa0

        [Extensions]
        2.5.29.17 = `"{text}`"
        "@

        foreach ($dns in $SanDNS) {
            $infContent += "`n_continue_ = `"dns=$dns`""
        }
        foreach ($ip in $SanIPs) {
            $infContent += "`n_continue_ = `"ipaddress=$ip`""
        }

        Set-Content -Path $InfPath -Value $infContent -Encoding ASCII
        certreq -new $InfPath $CsrPath
      args:
        executable: powershell

    - name: Fetch CSR file to controller
      win_fetch:
        src: "{{ csr_path }}"
        dest: "./csr_files/{{ common_name }}.req"
        flat: yes
