---
- name: Generate CSR on Windows host
  hosts: 192.168.1.11
  gather_facts: no

  collections:
    - community.windows

  vars:
    country: "{{ country }}"
    state: "{{ state }}"
    city: "{{ city }}"
    organization: "{{ organization }}"
    unit: "{{ unit }}"
    common_name: "{{ common_name }}"
    san_dns:
      - "{{ san1 | default('') }}"
      - "{{ san2 | default('') }}"
    san_ips:
      - "{{ ip1 | default('') }}"
      - "{{ ip2 | default('') }}"
    inf_path: "C:\\temp\\csr_request.inf"
    csr_path: "C:\\temp\\csr_request.req"

  tasks:
    - name: Ensure CSR directory exists
      community.windows.win_file:
        path: "C:\\temp"
        state: directory

    - name: Create empty INF file
      community.windows.win_file:
        path: "{{ inf_path }}"
        state: touch

    - name: Add base CSR config to INF file
      community.windows.win_lineinfile:
        path: "{{ inf_path }}"
        line: "{{ item }}"
        create: yes
      loop:
        - "[Version]"
        - "Signature=\"$Windows NT$\""
        - ""
        - "[NewRequest]"
        - "Subject = \"C={{ country }}, ST={{ state }}, L={{ city }}, O={{ organization }}, OU={{ unit }}, CN={{ common_name }}\""
        - "KeySpec = 1"
        - "KeyLength = 2048"
        - "Exportable = TRUE"
        - "MachineKeySet = TRUE"
        - "SMIME = FALSE"
        - "PrivateKeyArchive = FALSE"
        - "UserProtected = FALSE"
        - "UseExistingKeySet = FALSE"
        - "ProviderName = \"Microsoft RSA SChannel Cryptographic Provider\""
        - "ProviderType = 12"
        - "RequestType = PKCS10"
        - "KeyUsage = 0xa0"
        - ""
        - "[Extensions]"
        - "2.5.29.17 = \"{text}\""

    - name: Add DNS SAN entries
      community.windows.win_lineinfile:
        path: "{{ inf_path }}"
        line: "_continue_ = \"dns={{ item }}\""
        insertafter: EOF
      loop: "{{ san_dns }}"
      when: item | length > 0

    - name: Add IP SAN entries
      community.windows.win_lineinfile:
        path: "{{ inf_path }}"
        line: "_continue_ = \"ipaddress={{ item }}\""
        insertafter: EOF
      loop: "{{ san_ips }}"
      when: item | length > 0

    - name: Generate CSR using certreq
      community.windows.win_shell: certreq -new "{{ inf_path }}" "{{ csr_path }}"
      args:
        executable: cmd

    - name: Fetch CSR file to controller
      community.windows.win_fetch:
        src: "{{ csr_path }}"
        dest: "./csr_files/{{ common_name }}.req"
        flat: yes
