---
- name: Generate CSR on Windows host
  hosts: 192.168.1.11
  gather_facts: no
  vars:
    country: "{{ country }}"
    state: "{{ state }}"
    city: "{{ city }}"
    organization: "{{ organization }}"
    unit: "{{ unit }}"
    common_name: "{{ common_name }}"
    san_dns:
      - "{{ san1 }}"
      - "{{ san2 }}"
    san_ips:
      - "{{ ip1 }}"
      - "{{ ip2 }}"
    inf_path: "C:\\temp\\csr_request.inf"
    csr_path: "C:\\temp\\csr_request.req"

  tasks:
    - name: Ensure INF file exists
      win_file:
        path: "{{ inf_path }}"
        state: touch

    - name: Append CSR configuration to INF file
      win_shell: |
        Add-Content -Path "{{ inf_path }}" -Value "[Version]"
        Add-Content -Path "{{ inf_path }}" -Value "Signature=`"$Windows NT$`""
        Add-Content -Path "{{ inf_path }}" -Value ""
        Add-Content -Path "{{ inf_path }}" -Value "[NewRequest]"
        Add-Content -Path "{{ inf_path }}" -Value "Subject = `"C={{ country }}, ST={{ state }}, L={{ city }}, O={{ organization }}, OU={{ unit }}, CN={{ common_name }}`""
        Add-Content -Path "{{ inf_path }}" -Value "KeySpec = 1"
        Add-Content -Path "{{ inf_path }}" -Value "KeyLength = 2048"
        Add-Content -Path "{{ inf_path }}" -Value "Exportable = TRUE"
        Add-Content -Path "{{ inf_path }}" -Value "MachineKeySet = TRUE"
        Add-Content -Path "{{ inf_path }}" -Value "SMIME = FALSE"
        Add-Content -Path "{{ inf_path }}" -Value "PrivateKeyArchive = FALSE"
        Add-Content -Path "{{ inf_path }}" -Value "UserProtected = FALSE"
        Add-Content -Path "{{ inf_path }}" -Value "UseExistingKeySet = FALSE"
        Add-Content -Path "{{ inf_path }}" -Value "ProviderName = `"Microsoft RSA SChannel Cryptographic Provider`""
        Add-Content -Path "{{ inf_path }}" -Value "ProviderType = 12"
        Add-Content -Path "{{ inf_path }}" -Value "RequestType = PKCS10"
        Add-Content -Path "{{ inf_path }}" -Value "KeyUsage = 0xa0"
        Add-Content -Path "{{ inf_path }}" -Value ""
        Add-Content -Path "{{ inf_path }}" -Value "[Extensions]"
        Add-Content -Path "{{ inf_path }}" -Value "2.5.29.17 = `"{text}`""
{% for dns in san_dns %}
        Add-Content -Path "{{ inf_path }}" -Value "_continue_ = `"dns={{ dns }}`""
{% endfor %}
{% for ip in san_ips %}
        Add-Content -Path "{{ inf_path }}" -Value "_continue_ = `"ipaddress={{ ip }}`""
{% endfor %}

    - name: Generate CSR using certreq
      win_shell: certreq -new "{{ inf_path }}" "{{ csr_path }}"

    - name: Fetch CSR file to controller
      win_fetch:
        src: "{{ csr_path }}"
        dest: "./csr_files/{{ common_name }}.req"
        flat: yes
