---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
#      hostname: 
#      username: 
#      password: 
      validate_certs: False
      name: ansible-test-vm1
      template: ansible-template 
      datacenter: dc1
      folder: /dc1/vm
      state: poweredon
      cluster: cl1
      wait_for_ip_address: no
