- name: Delete all snapshots from all VMs in vCenter
  hosts: localhost
  gather_facts: false

  vars:
#    vcenter_hostname: "your-vcenter-host"
#    vcenter_username: "your-username"
#    vcenter_password: "your-password"
    datacenter_name: "sfo-m01-dc01"

  tasks:
    - name: Retrieve all virtual machines
      community.vmware.vmware_vm_info:
 #       hostname: "{{ vcenter_hostname }}"
 #       username: "{{ vcenter_username }}"
 #       password: "{{ vcenter_password }}"
        validate_certs: no
      register: vm_list

    - name: Remove all snapshots from each VM (skipping system VMs)
      community.vmware.vmware_guest_snapshot:
  #      hostname: "{{ vcenter_hostname }}"
  #      username: "{{ vcenter_username }}"
  #      password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ item.guest_name }}"
        folder: "{{ item.folder }}"
        state: remove_all
        validate_certs: no
      loop: "{{ vm_list.virtual_machines }}"
      when:
        - item.guest_name is defined
        - item.folder is defined
        - not item.guest_name.startswith('vCLS-')
      loop_control:
        label: "{{ item.guest_name }}"
      ignore_errors: true  # Optional: continue even if one VM fails
