---
- name: Deploy VM from template via AWX
  hosts: localhost
  gather_facts: false
  vars:
#    vcenter_hostname: "vcenter.example.com"
#    vcenter_username: "administrator@vsphere.local"
#    vcenter_password: "your_password"
    datacenter_name: "dc1"
    cluster_name: "cl1"
    template_name: "ansible-template"
    vm_name: "ansible-test-vm1"
    vm_folder: "/dc1/vm"
  tasks:
    - name: Deploy VM from template
      community.vmware.vmware_guest:
#        hostname: "{{ vcenter_hostname }}"
#        username: "{{ vcenter_username }}"
#        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ datacenter_name }}"
        folder: "{{ vm_folder }}"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        cluster: "{{ cluster_name }}"
        state: poweredon
        wait_for_ip_address: true
